feat!: add support for Angular 21

diff --git a/.github/workflows/cherry-pick.yml b/.github/workflows/cherry-pick.yml
--- a/.github/workflows/cherry-pick.yml
+++ b/.github/workflows/cherry-pick.yml
@@ -9,19 +9,19 @@ on:
 env:
   TARGET_BRANCH: main
   FROM_BRANCH: ${{ github.event.pull_request.base.ref }}
+  RUN_MIGRATIONS: 0
 
 jobs:
   cherry-pick:
     if: github.event.pull_request.merged == true
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v5
         with:
           ref: ${{ env.TARGET_BRANCH }}
           fetch-depth: 0
           token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
-
-      - uses: actions/setup-node@v4
+      - uses: actions/setup-node@v5
         id: setup-node
         with:
           cache: 'npm'
@@ -52,6 +52,39 @@ jobs:
             exit 0
           fi
 
+
+          if [ $RUN_MIGRATIONS -gt 0 ]; then
+            # Capture @angular/core migrations.
+            FROM_VERSION=$(git cat-file --textconv origin/${{ env.FROM_BRANCH }}:package.json | jq -r '.dependencies["@angular/core"]')
+            TO_VERSION=$(jq -r '.dependencies["@angular/core"]' package.json)
+            npx nx migrate @angular/core \
+              --from="@angular/core@${FROM_VERSION}" \
+              --to="@angular/core@${TO_VERSION}"
+
+            # Remove migrations that are not needed for cherry-picks. They take too long to run and should not apply.
+            jq -r '.migrations | map(select(.name != "inject-flags")) | map(select(.name != "test-bed-get")) | {"migrations": .}' migrations.json >  migrations.json.tmp \
+              && mv migrations.json.tmp migrations.json
+
+            # Run the migrations and fix any formatting issues.
+            npx nx migrate --run-migrations --if-exists && npx nx format:write
+
+            if [ $? -ne 0 ]; then
+              echo "CHERRY_PICK_RESULT=failed" >> $GITHUB_ENV
+              exit 0
+            fi
+
+            rm -f ./migrations.json
+            # Any changes to package.json and package-lock.json should not be committed.
+            git restore package.json package-lock.json
+            git add -A
+            git status
+            if [ -n "$(git status --porcelain)" ]; then
+              git commit --amend --no-edit
+            fi
+          else
+            echo "Skipping migrations 🙈"
+          fi
+
           # Get the name of the cherry-pick branch.
           CHERRY_PICK_BRANCH=$(git branch --show-current)
           # Add the cherry-pick branch to the environment.
@@ -69,7 +102,7 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
 
-      - uses: actions/github-script@v7
+      - uses: actions/github-script@v8
         if: ${{ env.CHERRY_PICK_RESULT != 'failed' }}
         with:
           github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
@@ -92,21 +125,18 @@ jobs:
               console.log(`Created PR #${result.data.number}: ${result.data.html_url}`);
               core.exportVariable('PR_URL', result.data.html_url);
               core.exportVariable('CHERRY_PICK_RESULT', 'success');
-              const riskLabels = pr.labels.map(label => label.name).filter(label => label.startsWith('risk level'));
-              if (riskLabels.length === 0) {
-                if (pr.labels.find(label => label.name.startsWith('autorelease'))) {
+              const labels = pr.labels.map(label => label.name).filter(label => label.startsWith('risk level') || label === 'skip e2e');
+              const assignees = pr.user.login && pr.user.type === 'User' && pr.user.login !== 'blackbaud-sky-build-user' ? [pr.user.login] : [];
+              if (labels.length === 0 && pr.labels.find(label => label.name.startsWith('autorelease'))) {
                   // Changelog PR, so add minimal risk level labels.
-                  riskLabels.push('risk level (author): 1', 'risk level (reviewer): 1');
-                } else {
-                  // No risk level label found, so don't add any.
-                  return;
-                }
+                labels.push('risk level (author): 1');
               }
               return github.rest.issues.update({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 issue_number: result.data.number,
-                labels: riskLabels
+                assignees: assignees,
+                labels: labels
               });
             }).catch(error => {
               console.log(error);
@@ -116,7 +146,7 @@ jobs:
 
       - name: Comment on the original PR when cherry-pick is successful
         if: ${{ env.CHERRY_PICK_RESULT == 'success' }}
-        uses: actions/github-script@v7
+        uses: actions/github-script@v8
         with:
           github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
           script: |
@@ -129,7 +159,7 @@ jobs:
 
       - name: Comment on the original PR when cherry-pick fails
         if: ${{ env.CHERRY_PICK_RESULT != 'success' }}
-        uses: actions/github-script@v7
+        uses: actions/github-script@v8
         with:
           github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
           script: |
@@ -142,7 +172,7 @@ jobs:
 
       - name: Notify Slack when cherry-pick fails
         if: ${{ env.CHERRY_PICK_RESULT != 'success' }}
-        uses: rtCamp/action-slack-notify@v2
+        uses: rtCamp/action-slack-notify@07cbdbfd6c6190970778d8f98f11d073b2932aae # v2.3.3
         env:
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
           SLACK_TITLE: ':cherries: :x: Cherry-pick failed for “${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number}})”'
